# Generated by Django 3.2.7 on 2021-10-06 22:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('header_image', models.ImageField(upload_to='images/bars')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('has_table_games', models.BooleanField()),
                ('has_video_games', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('bar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='bars.bar')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('header_image', models.ImageField(upload_to='images/events')),
                ('date', models.DateTimeField()),
                ('article', djrichtextfield.models.RichTextField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=25)),
                ('zip_code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000, message='Un code postal Belge doit être plus grand ou égal à 1000'), django.core.validators.MaxValueValidator(9999, message='Un code postal Belge doit être plus petit ou égal à 9999')])),
                ('city', models.CharField(max_length=50)),
                ('bar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='bars.bar')),
            ],
        ),
    ]
