# Generated by Django 3.2.7 on 2021-10-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='bars.bar'),
        ),
    ]
