# Generated by Django 3.2.7 on 2021-10-10 11:32

import bars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_auto_20211007_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveSmallIntegerField(validators=[bars.validators.validate_zip_code]),
        ),
        migrations.AlterField(
            model_name='bar',
            name='header_image',
            field=models.ImageField(upload_to='images/bars/bars'),
        ),
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(upload_to='images/bars/events'),
        ),
    ]
