# Generated by Django 3.2.7 on 2021-10-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_auto_20211010_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='header_image',
            field=models.ImageField(upload_to='bars/images/bars'),
        ),
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(upload_to='bars/images/events'),
        ),
    ]
