# Generated by Django 3.2.7 on 2021-10-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_auto_20211012_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='bars/images/games')),
            ],
        ),
    ]
