# Generated by Django 3.2.7 on 2021-10-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='games',
            field=models.ManyToManyField(related_name='bars', to='bars.Game'),
        ),
    ]
